name: auth_feature
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  auth_feature_repository_base:
    git:
      url: git://github.com/KamiTzayig/flutter_auth_feature.git
      path: auth_feature_repository_base
      ref: main  # Specify the branch or commit hash you want to use.

  firebase_auth_feature_repository:
    git:
      url: git://github.com/KamiTzayig/flutter_auth_feature.git
      path: firebase_auth_feature_repository
      ref: main  # Specify the branch or commit hash you want to use.

  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  supabase_auth_feature_repository:
    git:
      url: git://github.com/KamiTzayig/flutter_auth_feature.git
      path: supabase_auth_feature_repository
      ref: main  # Specify the branch or commit hash you want to use.


dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.4
  lints: ^3.0.0
  riverpod_generator: ^2.3.5
  test: ^1.21.0
