name: firebase_auth_feature_repository
description: A sample command-line application.
version: 1.0.4
repository: https://github.com/KamiTzayig/flutter_auth_feature/firebase_auth_feature_repository

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  auth_feature_repository_base:
    git:
      url: git://github.com/KamiTzayig/flutter_auth_feature.git
      path: auth_feature_repository_base
      ref: main  # Specify the branch or commit hash you want to use.
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  google_sign_in: ^6.1.5


  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
